# Generated by Django 4.2.15 on 2025-02-16 16:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="NG", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country_of_birth",
            field=django_countries.fields.CountryField(
                default="NG", max_length=2, verbose_name="Country of Birth"
            ),
        ),
    ]
