# Generated by Django 4.2.15 on 2025-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_profile_country_alter_profile_country_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us-dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("nigeria-naira", "Nigeria Naira"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("current", "Current"), ("savings", "Savings")],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
    ]
